package the8puzzle;

/**
 * The main board for the EightPuzzle game.
 *
 * @author Antonio
 */
public class EightBoard extends javax.swing.JFrame {
    private EightTile eightTile1;
    private EightTile eightTile2;
    private EightTile eightTile3;
    private EightTile eightTile4;
    private EightTile eightTile5;
    private EightTile eightTile6;
    private EightTile eightTile7;
    private EightTile eightTile8;
    private EightTile eightTile9;
    private EightStatus eightStatus;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton flipButton;

    private EightTile[] eightTiles;
    private EightController eightController;

    /**
     * Initialise the board and start a new game.
     */
    public EightBoard() {
        initComponents();

        // Initialise eightController and register listeners
        eightTiles = new EightTile[] { eightTile1, eightTile2, eightTile3, eightTile4, eightTile5, eightTile6,
                eightTile7, eightTile8, eightTile9 };
        eightController = new EightController();

        for (EightTile eightTile : eightTiles) {
            eightTile.addVetoableChangeListener(eightController);
            eightController.addTileListener(eightTile);
        }

        eightController.addStatusListener(eightStatus);

        // Start a New Game
        eightController.startNewGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        eightTile1 = new EightTile(1);
        eightTile2 = new EightTile(2);
        eightTile3 = new EightTile(3);
        eightTile4 = new EightTile(4);
        eightTile5 = new EightTile(5);
        eightTile6 = new EightTile(6);
        eightTile7 = new EightTile(7);
        eightTile8 = new EightTile(8);
        eightTile9 = new EightTile(9);
        eightStatus = new EightStatus();
        restartButton = new javax.swing.JButton();
        flipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 3));
        getContentPane().add(eightTile1);
        getContentPane().add(eightTile2);
        getContentPane().add(eightTile3);
        getContentPane().add(eightTile4);
        getContentPane().add(eightTile5);
        getContentPane().add(eightTile6);
        getContentPane().add(eightTile7);
        getContentPane().add(eightTile8);
        getContentPane().add(eightTile9);
        getContentPane().add(eightStatus);

        restartButton.setText("RESTART");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartGame(evt);
            }
        });
        getContentPane().add(restartButton);

        flipButton.setText("FLIP");
        flipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(flipButton);

        pack();
    }

    private void restartGame(java.awt.event.ActionEvent evt) {
        eightController.startNewGame();
    }

    private void flipButtonActionPerformed(java.awt.event.ActionEvent evt) {
        eightController.flip(eightTile1.getTileLabel(), eightTile2.getTileLabel());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EightBoard().setVisible(true);
            }
        });
    }
}
